version: '3'
services:
  node1:
    build:
      context: /www/node1
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks:
      app-network:
        ipv4_address: 172.28.0.2
  node2:
    build:
      context: /www/node2
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
    networks:
      app-network:
        ipv4_address: 172.28.0.3
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.28.0.4
      
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
