- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker engine
  apt:   
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: ['docker-ce','docker-ce-cli','containerd.io']
