- name: Creates directory
  file:
    path: /www
    state: directory
    
- name:
  copy:
    src: ./www/
    dest: /www/

- name: Install pip3
  apt:
    name: python3-pip

- name: Install docker-compose module
  pip:
    name: docker-compose

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Build & run docker-compose
  docker_compose:
    project_src: /www
    build: yes
  register: output
